teleop_twist_joy_node:
  ros__parameters:

    axis_linear:
      x: 1
      y: 3

    scale_linear:
    
      x: 0.25
      y: 0.25
    scale_linear_turbo:
      x: 0.35
      y: 0.35

    axis_angular:
      yaw: 0

    scale_angular:
      yaw: 0.09

    scale_angular_turbo:
      yaw: 0.15

    enable_button: 5
    enable_turbo_button: 4 